#!/usr/bin/env bash
# Script to transfer a file from our client to a server

usg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ $# -gt 3 ]; then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
else
    echo "$usg"
fi
