#!/usr/bin/env bash
# Installs and configures HAproxy on the load balancer

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 438926-web-01 100.25.137.200:80 check
   server 438926-web-02 54.196.200.137:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
