#!/usr/bin/env bash
# Configures an Nginx server

mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
