#!/usr/bin/env bash
# displays a message indefinitely
# displays "I am invicible!!!" when receiving a SIGTERM

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
